-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnhBnulpaBQ4GEYgB
fmn/h8T9FW33ZfpGPBWKbJBr3ymgCgYIKoZIzj0DAQehRANCAATIANOO3tnZm9UJ
hQs0g8vLmgecNtZorOQxSS1H+87blHBvMduoGHU85FD1nWayRqvHRPGzs5RgLmXp
fqHAhJvp
-----END PRIVATE KEY-----